name: pit02gp07
description: A new Flutter project.


publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"


dependencies:


  bloc_test: ^9.1.0
  cloud_firestore: ^4.2.0
  cubit: ^0.1.2
  dropdown_textfield: ^1.0.7
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_auth: ^4.2.0
  firebase_auth_mocks: ^0.10.3
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_credit_card: ^3.0.5
  flutter_expandable_fab: ^1.6.1
  flutter_masked_text2: ^0.9.1
  flutter_modular: ^5.0.3
  flutter_slidable: ^2.0.0
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.6
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15

dev_dependencies:

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/images/
 